# Generated by Django 6.0.2 on 2026-02-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_team',
            field=models.BooleanField(default=False),
        ),
    ]
