# Generated by Django 6.0.2 on 2026-02-23 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_category_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='main_category',
        ),
        migrations.AddField(
            model_name='category',
            name='maincategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_app.maincategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='maincategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.maincategory'),
        ),
    ]
