# Generated by Django 6.0.2 on 2026-02-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_remove_category_main_category_category_maincategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='maincategory',
            new_name='main_category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='maincategory',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
