# Generated by Django 6.0.2 on 2026-02-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_rename_maincategory_category_main_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, max_length=420, null=True),
        ),
    ]
