# Generated by Django 6.0.2 on 2026-02-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_subcategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chef_images/')),
            ],
        ),
    ]
