# Generated by Django 6.0.2 on 2026-02-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
