# Generated by Django 6.0.2 on 2026-03-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_chef_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
