# Generated by Django 6.0.2 on 2026-03-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_subcategory_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
