# Generated by Django 6.0.2 on 2026-03-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_subcategory_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='quantity',
        ),
    ]
