# Generated by Django 6.0.2 on 2026-03-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_remove_subcategory_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('delivered_at', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('gst', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
