# Generated by Django 6.0.2 on 2026-03-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='vat_status',
            field=models.CharField(choices=[('include', 'VAT include'), ('vatl_include', 'VATL include'), ('not_include', 'Not include')], default='not_include', max_length=20),
        ),
    ]
