# Generated by Django 6.0.2 on 2026-02-28 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0002_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=10)),
                ('subtotal', models.FloatField()),
                ('gst', models.FloatField()),
                ('totalamount', models.FloatField()),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_app.order')),
            ],
        ),
    ]
