# Generated by Django 6.0.2 on 2026-03-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChefDeliveredOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('table_number', models.CharField(max_length=50)),
                ('placed_at', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('gst', models.FloatField()),
                ('total', models.FloatField()),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
