# Generated by Django 6.0.2 on 2026-03-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
