# Generated by Django 6.0.2 on 2026-03-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='zipcode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
