# Generated by Django 6.0.2 on 2026-03-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_userorder_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
