# Generated by Django 6.0.2 on 2026-03-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_userorderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOrderItem',
        ),
    ]
