# Generated by Django 6.0.2 on 2026-03-06 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_delete_userorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hotel.userorder')),
            ],
        ),
    ]
